site_name: Blogs

repo_url: https://github.com/LucasLan666666/LucasLan666666.github.io

repo_name: LucasLan666666.github.io

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjex.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  # - https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.7.0/lxgwwenkaiscreen.css

nav:
  - Home: index.md
  - About: about.md
  - Experiences:
  #   - Markdown: Experiences/Markdown 常用模板.md
  #   - Mermaid: Experiences/mermaid/Mermaid 踩坑日记.md
    - Github-Copilot: Experiences/copilot/main.md
  #   - Git: Experiences/Git 入坑指南.md
  - UCAS:
    - Digital Circuit:
      - Lab1: UCAS/Digital-Circuit/1/main.md
      - Lab2: UCAS/Digital-Circuit/2/main.md
      - Lab3: UCAS/Digital-Circuit/3/main.md
      - Lab4: UCAS/Digital-Circuit/4/main.md
    - Assembly Language:
      - LoooooooooongArch: UCAS/Assembly-Language/LoongArch.md
      - quicksort: UCAS/Assembly-Language/quicksort.md
    - COD-Lab:
      - bhv_sim_env: UCAS/COD-Lab/bhv_sim_env.md
      - prj3: UCAS/COD-Lab/prj3.md
  - Tools:
    - personal: personal.md
  # - Test:
  #     - Latex: test/Latex test.md
  #     - font: test/font.md

theme:
    name: material
    icon:
        repo: fontawesome/brands/git-alt
    logo: assets/faye.png # logo
    favicon: images/cat.ico  # favicon
    font:
        text: Noto Sans SC
        # text: Montserrat
        # text: Noto Serif SC
        # text: Zen Old Mincho
        # text: LXGW WenKai Screen
        code: JetBrains Mono
    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    features:
      - content.code.copy
      - content.code.annotate
      - navigation.instant #- header.autohide  #自动隐藏
      #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
      - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
      - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
      - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
      - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
      - navigation.top # 返回顶部的按钮 在上滑时出现
      - search.suggest # 搜索输入一些字母时推荐补全整个单词
      - search.highlight # 搜索出的文章关键词加入高亮
      - search.share #搜索分享按钮
      - navigation.expand # 打开Tab时左侧目录全部展开
      - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    # language: zh # 一些提示性的文字会变成中文

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols  # 符号转换
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  # - toc:
  #     permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences: # 代码块高亮插件
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta # 支持Markdown文件上方自定义标题标签等

plugins:
    - search:
        separator: '[\s\u200b\-]'
        lang: ja
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: true
        manual: false
    # - social
